# -*- coding: utf-8 -*-
"""FrequencyOfWordsPython.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uj4DbjP7yDCsUJ2CyUvbQzIjBedaJN-g
"""

#JuarezRamirezLuis
import requests
from bs4 import BeautifulSoup

url = 'https://www.dof.gob.mx/nota_detalle.php?codigo=5687777&fecha=04/05/2023#gsc.tab=0'
fr = []
a=requests.get(url, verify=False).text
soup = BeautifulSoup(a, 'html.parser')
clean_text = soup.get_text()
clean_text = clean_text.lower()

def count(elements):
	if elements[-1] == '.':
		elements = elements[0:len(elements) - 1]
	if elements in dictionary:
		dictionary[elements] += 1
	else:
		dictionary.update({elements: 1})

Sentence = clean_text
dictionary = {}
lst = Sentence.split()
for elements in lst:
	count(elements)

for allKeys in dictionary:
	print ("Frecuencia de ", allKeys, end = " ")
	print (":", end = " ")
	print (dictionary[allKeys], end = " ")
	print()